### ISSUE TITLE
I need help with compilation

### ISSUE THREAD

**Issue by khushal-banks** [jgabaut/sprites4curses#90]
**Not able to generate demo executable**
I cloned this repository then i installed pillow using pip. I followed the steps in README to compile for demo project.
make command is returning errors.

**To Reproduce**
1. Clone Repo
2. cd Repo
3. Clone scripts repo
4. Compile using recommended steps in README
```
# EDIT: I used following steps to compile from README
autoreconf; automake --add-missing; autoreconf; automake --add-missing autoreconf; ./configure make; ./demo demofile.txt
```

**Executable file: demo**
Program should compile. What am i missing?

**Screenshot**

I tried ./configure and make as separate commands in resulted in following error.
![image](https://github.com/jgabaut/sprites4curses/assets/156434242/09e7f3e9-61f3-47b6-90bc-0daaef87b518)

then, i rechecked README they are not separate commands so joined them then this error.
![image](https://github.com/jgabaut/sprites4curses/assets/156434242/1e0aa2ab-78f3-4c3f-940f-eb9dcee78dbd)

then, i modified the Makefile and removed -Wpedantic .. tried to make. still error
![image](https://github.com/jgabaut/sprites4curses/assets/156434242/af6b3c56-8ca3-4742-bafc-0115e1cd4f1f)

**Desktop**
 - OS: [Arch Linux]
 - Version [Latest]

I am new to all this.
Can you help me compile this?

**Comment by jgabaut** [comment]
To build the demo, you also need to generate palette.c from palette.gpl 


In readme:


`python, to generate ./s4c-animate/palette.h and ./s4c-animate/palette.c from ./palette.gpl`


In Makefile.am:


```am
PALETTE_PATH = ./palette.gpl


s4c-animate/palette.c:

        @echo -en "Generating \033[1;35mpalette.c\e[0m and \033[1;35mpalette.h\e[0m from [$(PALETTE_PATH)]:  "

        python scripts/palette.py C-header $(PALETTE_PATH) ../.. > s4c-animate/palette.h

        python scripts/palette.py C-impl $(PALETTE_PATH) ../.. > s4c-animate/palette.c

        @echo -e "Done."


```

**Comment by khushal-banks** [comment]
Your suggestion solved my issue.
I had no idea how to use makefile to generate palette files.
So, i manually typed,
```
python scripts/palette.py C-header ./palette.gpl ../.. > s4c-animate/palette.h 
python scripts/palette.py C-impl ./palette.gpl ../.. > s4c-animate/palette.c
```

No your README is fine. No change required. It is my skill issue.
But i would recommend to put a semicolon between ./configure make
> I am not sure .. see if a semicolon is required.

**Comment by jgabaut** [comment]
> No your README is fine. No change required.

I really meant it should be cleaned, especially the build instructions (more on this later) are very messy. I just couldn't be bothered to fix it... But I'll try to do it soon.


> But i would recommend to put a semicolon between ./configure make

That part is totally scuffed because I didn't really check the markdown before committing, and was expecting a different render with some newlines... Or something like that, can't really remember 100%. Still, you're right, it reads as a big shell error, the whole build instructions scream "please semicolon".

> I had no idea how to use makefile to generate palette files.

This is something that came to my mind and I'll have to check if the makefile has problems from a fresh copy (since I haven't really regenerated my `palette.c` in a while).

Thanks for pointing that out, I'll have to open a separate issue if I find out in a more definite way what's wrong. Will reference this issue there. I'm guessing the `palette.c` Makefile rule was not executed. I'll see.

**Comment by khushal-banks** [comment]
You are the most close to a friend i have on github. I didn't misunderstand you. 
This compilation method is really good but was new to me. (so i mentioned skill)

It was great to find out about ncurses and raylib .. i didn't know c could produce animation so easily. Great work brother. :)
Thank you for sharing this repository.
